// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.8
// source: game.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameServiceClient interface {
	//Bidirectional Chat
	TicTacToeGame(ctx context.Context, opts ...grpc.CallOption) (GameService_TicTacToeGameClient, error)
}

type gameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameServiceClient(cc grpc.ClientConnInterface) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) TicTacToeGame(ctx context.Context, opts ...grpc.CallOption) (GameService_TicTacToeGameClient, error) {
	stream, err := c.cc.NewStream(ctx, &GameService_ServiceDesc.Streams[0], "/game.GameService/TicTacToeGame", opts...)
	if err != nil {
		return nil, err
	}
	x := &gameServiceTicTacToeGameClient{stream}
	return x, nil
}

type GameService_TicTacToeGameClient interface {
	Send(*GameRequest) error
	Recv() (*GameResponse, error)
	grpc.ClientStream
}

type gameServiceTicTacToeGameClient struct {
	grpc.ClientStream
}

func (x *gameServiceTicTacToeGameClient) Send(m *GameRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gameServiceTicTacToeGameClient) Recv() (*GameResponse, error) {
	m := new(GameResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GameServiceServer is the server API for GameService service.
// All implementations must embed UnimplementedGameServiceServer
// for forward compatibility
type GameServiceServer interface {
	//Bidirectional Chat
	TicTacToeGame(GameService_TicTacToeGameServer) error
	mustEmbedUnimplementedGameServiceServer()
}

// UnimplementedGameServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGameServiceServer struct {
}

func (UnimplementedGameServiceServer) TicTacToeGame(GameService_TicTacToeGameServer) error {
	return status.Errorf(codes.Unimplemented, "method TicTacToeGame not implemented")
}
func (UnimplementedGameServiceServer) mustEmbedUnimplementedGameServiceServer() {}

// UnsafeGameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServiceServer will
// result in compilation errors.
type UnsafeGameServiceServer interface {
	mustEmbedUnimplementedGameServiceServer()
}

func RegisterGameServiceServer(s grpc.ServiceRegistrar, srv GameServiceServer) {
	s.RegisterService(&GameService_ServiceDesc, srv)
}

func _GameService_TicTacToeGame_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GameServiceServer).TicTacToeGame(&gameServiceTicTacToeGameServer{stream})
}

type GameService_TicTacToeGameServer interface {
	Send(*GameResponse) error
	Recv() (*GameRequest, error)
	grpc.ServerStream
}

type gameServiceTicTacToeGameServer struct {
	grpc.ServerStream
}

func (x *gameServiceTicTacToeGameServer) Send(m *GameResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gameServiceTicTacToeGameServer) Recv() (*GameRequest, error) {
	m := new(GameRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GameService_ServiceDesc is the grpc.ServiceDesc for GameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TicTacToeGame",
			Handler:       _GameService_TicTacToeGame_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "game.proto",
}
