name: React CI

on:
  pull_request:

jobs:
    coverage:
        runs-on: ubuntu-latest
        name: Coverage report
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Test coverage
              uses: ./frontend
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  test-script: npm run test:coverage
            - name: Coverage Report
              uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                threshold: 80
