name: React CI

on:
  push:
  pull_request:

jobs:
  build_test_deploy:
    runs-on: ubuntu-18.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: |
          cd frontend
          npm i

      - name: Run Jest tests
        run: |
          cd frontend
          npm run test

      - name: Test
        run: |
          cd frontend
          npm run test

      - name: coverage
        run: |
          cd frontend
          npm run coverage
          echo '# Coverage :rocket:' >> $GITHUB_STEP_SUMMARY
          cat coverage/report.txt | sed '1d' | sed '$d' >> $GITHUB_STEP_SUMMARY

      # - name: Install Firebase Tools
      #   run: |
      #     npm install -g firebase-tools

      # - name: Deploy
      #   env:
      #     FIREBASE_TOKEN_PROD: ${{ secrets.FIREBASE_TOKEN_PROD }}
      #   run: |
      #     firebase deploy  --only hosting --project prod --token $FIREBASE_TOKEN_PROD